package pt.ulusofona.tfc.trabalho.form

import javax.validation.constraints.Min
import javax.validation.constraints.NotEmpty
import javax.validation.constraints.NotNull


data class FormularioForm2(

        //secção 7
        //7.1
        var s7_1 : Boolean = false,
        var s7_1_A : Boolean = false,
        var s7_1_B : Boolean = false,
        var s7_1_C : Boolean = false,
        var s7_1_D : Boolean = false,
        var s7_1_E : Boolean = false,
        var s7_1_F : Boolean = false,
        var s7_1_G : Boolean = false,
        var s7_1_H : Boolean = false,
        var s7_1_I : Boolean = false,
        var s7_1_I_f : String = "",
        var s7_1_J : Boolean = false,
        var s7_1_J_f : String = "",
        var s7_1_L : Boolean = false,
        var s7_1_L_f : String = "",
        var s7_1_M : Boolean = false,
        var s7_1_M_f : String = "",
        //7.2
        var s7_2 : Boolean = false,
        //7.2.1
        var s7_2_1_A : Boolean = false,
        var s7_2_1_B : Boolean = false,
        var s7_2_1_B_f : String = "",
        var s7_2_1_C : Boolean = false,
        var s7_2_1_C_f : String = "",
        //7.2.2
        var s7_2_2_A : Boolean = false,
        var s7_2_2_B : Boolean = false,
        var s7_2_2_C : Boolean = false,
        var s7_2_2_D : Boolean = false,
        var s7_2_2_E : Boolean = false,
        var s7_2_2_F : Boolean = false,
        var s7_2_2_G : Boolean = false,
        var s7_2_2_H : Boolean = false,
        var s7_2_2_I : Boolean = false,
        var s7_2_2_I_f : String = "",
        var s7_2_2_J : Boolean = false,
        var s7_2_2_J_f : String = "",
        var s7_2_2_L : Boolean = false,
        var s7_2_2_L_f : String = "",
        var s7_2_2_M : Boolean = false,
        var s7_2_2_M_f : String = "",
        //7.3
        var s7_3 : Boolean = false,
        //7.3.1
        var s7_3_1_A : Boolean = false,
        var s7_3_1_A_f : String = "",
        var s7_3_1_B : Boolean = false,
        var s7_3_1_B_f : String = "",
        //7.3.2
        var s7_3_2_A : Boolean = false,
        var s7_3_2_B : Boolean = false,
        var s7_3_2_C : Boolean = false,
        var s7_3_2_D : Boolean = false,
        var s7_3_2_E : Boolean = false,
        var s7_3_2_F : Boolean = false,
        var s7_3_2_G : Boolean = false,
        var s7_3_2_H : Boolean = false,
        var s7_3_2_I : Boolean = false,
        var s7_3_2_I_f : String = "",
        var s7_3_2_J : Boolean = false,
        var s7_3_2_J_f : String = "",
        var s7_3_2_L : Boolean = false,
        var s7_3_2_L_f : String = "",
        var s7_3_2_M : Boolean = false,
        var s7_3_2_M_f : String = "",
        //7.4
        var s7_4 : Boolean = false,
        //7.4.1
        var s7_4_1_A : Boolean = false,
        var s7_4_1_B : Boolean = false,
        var s7_4_1_B_f : String = "",
        //7.4.2
        var s7_4_2_A : Boolean = false,
        var s7_4_2_B : Boolean = false,
        var s7_4_2_C : Boolean = false,
        var s7_4_2_D : Boolean = false,
        var s7_4_2_E : Boolean = false,
        var s7_4_2_F : Boolean = false,
        var s7_4_2_G : Boolean = false,
        var s7_4_2_H : Boolean = false,
        var s7_4_2_I : Boolean = false,
        var s7_4_2_I_f : String = "",
        var s7_4_2_J : Boolean = false,
        var s7_4_2_J_f : String = "",
        var s7_4_2_L : Boolean = false,
        var s7_4_2_L_f : String = "",
        var s7_4_2_M : Boolean = false,
        var s7_4_2_M_f : String = "",
        var s7_4_2_O : Boolean = false,
        //7.5
        var s7_5 : Boolean = false,
        var s7_5_A : Boolean = false,
        var s7_5_B : Boolean = false,
        var s7_5_C : Boolean = false,
        var s7_5_D : Boolean = false,
        var s7_5_E : Boolean = false,
        var s7_5_F : Boolean = false,
        var s7_5_G : Boolean = false,
        var s7_5_H : Boolean = false,
        var s7_5_H_f : String = "",
        var s7_5_I : Boolean = false,
        var s7_5_I_f : String = "",
        var s7_5_J : Boolean = false,
        var s7_5_J_f : String = "",
        var s7_5_L : Boolean = false,
        var s7_5_L_f : String = "",
        //secção 8
        var s8 : String = "",
        //secção 9
        //9.1
        var s9_1 : Boolean = false,
        var s9_1_A : Boolean = false,
        var s9_1_B : Boolean = false,
        var s9_1_C : Boolean = false,
        var s9_1_D : Boolean = false,
        var s9_1_E : Boolean = false,
        var s9_1_E_f : String = "",
        //9.2
        var s9_2 : Boolean = false,
        var s9_2_A : Boolean = false,
        var s9_2_B : Boolean = false,
        var s9_2_C : Boolean = false,
        var s9_2_D : Boolean = false,
        var s9_2_E : Boolean = false,
        var s9_2_F : Boolean = false,
        var s9_2_G : Boolean = false,
        var s9_2_G_f : String = "",
        //9.3
        var s9_3 : Boolean = false,
        var s9_3_A : Boolean = false,
        var s9_3_B : Boolean = false,
        var s9_3_B_f : String = "",
        //9.4
        var s9_4 : Boolean = false,
        var s9_4_A : Boolean = false,
        var s9_4_B : Boolean = false,
        var s9_4_B_f : String = "",
        var s9_4_C : Boolean = false,
        var s9_4_C_f : String = "",
        var s9_4_D : Boolean = false,
        var s9_4_D_f : String = "",
        var s9_4_E : Boolean = false,
        var s9_4_E_f : String = "",
        var s9_4_F : Boolean = false,
        var s9_4_F_f : String = "",
        //9.4.1
        var s9_4_1 : String = "",
)