package pt.ulusofona.tfc.trabalho.dao

import javax.persistence.Entity
import javax.persistence.GeneratedValue
import javax.persistence.Id

@Entity
data class S7Formulario(
        @Id @GeneratedValue
        //secção 7
        val id: Long = 0,
        var processId: String,
                //7.1
        var s7_1 : Boolean = false,
        var s7_1_A : Boolean = false,
        var s7_1_B : Boolean = false,
        var s7_1_C : Boolean = false,
        var s7_1_D : Boolean = false,
        var s7_1_E : Boolean = false,
        var s7_1_F : Boolean = false,
        var s7_1_G : Boolean = false,
        var s7_1_H : Boolean = false,
        var s7_1_I : Boolean = false,
        var s7_1_I_f : String = "",
        var s7_1_J : Boolean = false,
        var s7_1_J_f : String = "",
        var s7_1_L : Boolean = false,
        var s7_1_L_f : String = "",
        var s7_1_M : Boolean = false,
        var s7_1_M_f : String = "",
                //7.2
        var s7_2 : Boolean = false,
                //7.2.1
        var s7_2_1_A : Boolean = false,
        var s7_2_1_B : Boolean = false,
        var s7_2_1_B_f : String = "",
        var s7_2_1_C : Boolean = false,
        var s7_2_1_C_f : String = "",
                //7.2.2
        var s7_2_2_A : Boolean = false,
        var s7_2_2_B : Boolean = false,
        var s7_2_2_C : Boolean = false,
        var s7_2_2_D : Boolean = false,
        var s7_2_2_E : Boolean = false,
        var s7_2_2_F : Boolean = false,
        var s7_2_2_G : Boolean = false,
        var s7_2_2_H : Boolean = false,
        var s7_2_2_I : Boolean = false,
        var s7_2_2_I_f : String = "",
        var s7_2_2_J : Boolean = false,
        var s7_2_2_J_f : String = "",
        var s7_2_2_L : Boolean = false,
        var s7_2_2_L_f : String = "",
        var s7_2_2_M : Boolean = false,
        var s7_2_2_M_f : String = "",
                //7.3
        var s7_3 : Boolean = false,
                //7.3.1
        var s7_3_1_A : Boolean = false,
        var s7_3_1_A_f : String = "",
        var s7_3_1_B : Boolean = false,
        var s7_3_1_B_f : String = "",
                //7.3.2
        var s7_3_2_A : Boolean = false,
        var s7_3_2_B : Boolean = false,
        var s7_3_2_C : Boolean = false,
        var s7_3_2_D : Boolean = false,
        var s7_3_2_E : Boolean = false,
        var s7_3_2_F : Boolean = false,
        var s7_3_2_G : Boolean = false,
        var s7_3_2_H : Boolean = false,
        var s7_3_2_I : Boolean = false,
        var s7_3_2_I_f : String = "",
        var s7_3_2_J : Boolean = false,
        var s7_3_2_J_f : String = "",
        var s7_3_2_L : Boolean = false,
        var s7_3_2_L_f : String = "",
        var s7_3_2_M : Boolean = false,
        var s7_3_2_M_f : String = "",
                //7.4
        var s7_4 : Boolean = false,
                //7.4.1
        var s7_4_1_A : Boolean = false,
        var s7_4_1_B : Boolean = false,
        var s7_4_1_B_f : String = "",
                //7.4.2
        var s7_4_2_A : Boolean = false,
        var s7_4_2_B : Boolean = false,
        var s7_4_2_C : Boolean = false,
        var s7_4_2_D : Boolean = false,
        var s7_4_2_E : Boolean = false,
        var s7_4_2_F : Boolean = false,
        var s7_4_2_G : Boolean = false,
        var s7_4_2_H : Boolean = false,
        var s7_4_2_I : Boolean = false,
        var s7_4_2_I_f : String = "",
        var s7_4_2_J : Boolean = false,
        var s7_4_2_J_f : String = "",
        var s7_4_2_L : Boolean = false,
        var s7_4_2_L_f : String = "",
        var s7_4_2_M : Boolean = false,
        var s7_4_2_M_f : String = "",
        var s7_4_2_N : Boolean = false,
        var s7_4_2_N_f : String = "",
        var s7_4_2_O : Boolean = false,
                //7.5
        var s7_5 : Boolean = false,
        var s7_5_A : Boolean = false,
        var s7_5_B : Boolean = false,
        var s7_5_C : Boolean = false,
        var s7_5_D : Boolean = false,
        var s7_5_E : Boolean = false,
        var s7_5_F : Boolean = false,
        var s7_5_G : Boolean = false,
        var s7_5_H : Boolean = false,
        var s7_5_H_f : String = "",
        var s7_5_I : Boolean = false,
        var s7_5_I_f : String = "",
        var s7_5_J : Boolean = false,
        var s7_5_J_f : String = "",
        var s7_5_L : Boolean = false,
        var s7_5_L_f : String = "",
        )